version: 2.1
jobs:
    checkout:
        docker:
            - image: circleci/openjdk:11-jdk
              environment:
                  discovery.type: single-node
        steps:
            - checkout
            - run: sudo apt-get install openjdk-11-jdk-headless openjdk-8-jdk-headless
            - restore_cache:
                key: jrdsagent-{{ checksum "pom.xml" }}
            - run: mvn -B dependency:go-offline dependency:resolve-plugins
            - persist_to_workspace:
                root: ~
                paths:
                    .m2
            - persist_to_workspace:
                root: /
                paths:
                    /usr/lib/jvm/java-11-openjdk-amd64
    build:
        docker:
            - image: circleci/openjdk:11-jdk
              environment:
                  discovery.type: single-node
        steps:
            - run:
                command: mvn compile -Djdk.compile.home=/usr/lib/jvm/java-8-openjdk-amd64
                environment:
                    JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
            - run:
                command: |
                    # If no symbolic name, it's a PR, will not deploy
                    [ -n "$(git symbolic-ref HEAD 2>/dev/null )" ] && PUBLISH="deploy sonar:sonar"
                    echo "publishing jobs: $PUBLISH"
                    mvn install $PUBLISH -Dmaven.test.skip=true -Dmaven.main.skip=true -s .circleci/settings.xml -Djdk.compile.home=/usr/lib/jvm/java-8-openjdk-amd64
                environment:
                    JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
            - save_cache:
                paths:
                    - ~/.m2
                key: jrdsagent-{{ checksum "pom.xml" }}
            - store_test_results:
                path: target/surefire-reports
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - checkout
      - build:
          requires:
              - checkout
