version: 2.1
jobs:
    checkout:
        docker:
            - image: circleci/openjdk:13-jdk-buster
        steps:
            - checkout
            - restore_cache:
                key: jrdsagent-{{ checksum "pom.xml" }}
            - run:
                command: |
                    mkdir -p /home/circleci/.sonar/cache /home/circleci/.m2/repository
                    mvn -B dependency:go-offline -Psonar,versions -s .circleci/settings.xml
            - persist_to_workspace:
                root: /
                paths:
                    - home/circleci/.m2/repository
                    - home/circleci/.sonar/cache
                    - home/circleci/project
    jdk8_jre:
        docker:
            - image: circleci/openjdk:8-jdk
        steps:
            - persist_to_workspace:
                root: /usr/local
                paths:
                    - openjdk-8
    build:
        docker:
            - image: circleci/openjdk:13-jdk-buster
        steps:
            - attach_workspace:
                at: /tmp/ws
            - run:
                command: |
                    sudo mkdir -p /usr/lib/jvm
                    [ -d /tmp/ws/openjdk-8 ] && sudo mv -n /tmp/ws/openjdk-8 /usr/lib/jvm/java-8-openjdk-amd64
                    mv -n /tmp/ws/home/circleci/.m2 /home/circleci/
                    mv -n /tmp/ws/home/circleci/project/* /home/circleci/project/
                    mv -n /tmp/ws/home/circleci/project/.??* /home/circleci/project/
            - run:
                command: mvn -B clean compile install -DskipTests -s .circleci/settings.xml
                environment:
                    JAVA_HOME: /usr/java/openjdk-13
            - persist_to_workspace:
                root: /
                paths:
                    - home/circleci/.m2/repository
                    - home/circleci/project
    testsj8:
        docker:
            - image: circleci/openjdk:8-jdk
        steps:
            - attach_workspace:
                at: /tmp/ws
            - run:
                command: |
                    sudo mkdir -p /usr/lib/jvm
                    [ -d /tmp/ws/openjdk-8 ] && sudo mv -n /tmp/ws/openjdk-8 /usr/lib/jvm/java-8-openjdk-amd64
                    mv -n /tmp/ws/home/circleci/.m2 /home/circleci/
                    mv -n /tmp/ws/home/circleci/project/* /home/circleci/project/
                    mv -n /tmp/ws/home/circleci/project/.??* /home/circleci/project/
            - run:
                command: |
                    # If no symbolic name, it's a PR, will run sonar
                    if [ -n "$(git symbolic-ref HEAD 2>/dev/null )" ] ; then
                        SONAR="sonar:sonar -Psonar"
                        echo "Doing sonar"
                    else
                        SONAR=""
                    fi
                    #see https://stackoverflow.com/questions/53010200/maven-surefire-could-not-find-forkedbooter-class for disableClassPathURLCheck
                    mvn -B test $SONAR -Pskip -Dsonar.login=$SONARCLOUD_LOGIN -DargLine="-Xmx2048m -Djdk.net.URLClassPath.disableClassPathURLCheck=true" -s .circleci/settings.xml
                environment:
                    JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
                    MAVEN_OPTS: "-Xmx2048m"
            - store_test_results:
                path: target/surefire-reports
            #don't persist_to_workspace, can't be done in parallel with testsj11
    testsj11:
        docker:
            - image: circleci/openjdk:11-jdk
        steps:
            - attach_workspace:
                at: /tmp/ws
            - run:
                command: |
                    mv -n /tmp/ws/home/circleci/.m2 /home/circleci/
                    mv -n /tmp/ws/home/circleci/.sonar /home/circleci/
                    mv -n /tmp/ws/home/circleci/project/* /home/circleci/project/
                    mv -n /tmp/ws/home/circleci/project/.??* /home/circleci/project/
            - run:
                command: |
                    mvn -B test -Pskip -s .circleci/settings.xml
                environment:
                    JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
                    MAVEN_OPTS: "-Xmx2048m"
            - store_test_results:
                path: target/surefire-reports
            - persist_to_workspace:
                root: /
                paths:
                    - home/circleci/.m2/repository
                    - home/circleci/.sonar/cache
    publish:
        docker:
            - image: circleci/openjdk:13-jdk-buster
        steps:
            - attach_workspace:
                at: /tmp/ws
            - run:
                command: |
                    mv -n /tmp/ws/home/circleci/.m2 /home/circleci/
                    mv -n /tmp/ws/home/circleci/.sonar /home/circleci/
                    mv -n /tmp/ws/home/circleci/project/* /home/circleci/project/
                    mv -n /tmp/ws/home/circleci/project/.??* /home/circleci/project/
            - run:
                command: |
                    # If no symbolic name, it's a PR, will not publish results
                    if [ -n "$(git symbolic-ref HEAD 2>/dev/null )" ] ; then
                        PUBLISH="deploy"
                    else
                        PUBLISH="maven-install-plugin:install"
                    fi
                    echo "publishing jobs: $PUBLISH"
                    mvn -B $PUBLISH -Pskip -Dmaven.test.skip -s .circleci/settings.xml
                environment:
                    JAVA_HOME: /usr/java/openjdk-13
            - persist_to_workspace:
                root: /
                paths:
                    - home/circleci/.m2/repository
                    - home/circleci/.sonar/cache
    savecache:
        docker:
            - image: circleci/openjdk:13-jdk-buster
        steps:
            - attach_workspace:
                at: /tmp/ws
            - run:
                command: |
                    mv /tmp/ws/home/circleci/project/pom.xml /home/circleci/project/
                    mv /tmp/ws/home/circleci/.m2 /home/circleci/
                    mv /tmp/ws/home/circleci/.sonar /home/circleci/
            - save_cache:
                paths:
                    - /home/circleci/.m2/repository
                    - /home/circleci/.sonar/cache
                key: jrdsagent-{{ checksum "pom.xml" }}
            
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - checkout
      - jdk8_jre
      - build:
          requires:
              - checkout
              - jdk8_jre
      - testsj8:
          requires:
              - build
      - testsj11:
          requires:
              - build
      - publish:
          requires:
              - testsj8
              - testsj11
      - savecache:
          requires:
              - publish
