version: 2.1
jobs:
    checkout:
        docker:
            - image: circleci/openjdk:8-jdk
              environment:
                  discovery.type: single-node
        steps:
            - checkout
            - restore_cache:
                key: jrdsagent-{{ checksum "pom.xml" }}
            - persist_to_workspace:
                root: /
                paths:
                #    - usr/lib/jvm/java-8-openjdk-amd64
                    - home/circleci/project
    build:
        docker:
            - image: circleci/openjdk:11-jdk
              environment:
                  discovery.type: single-node
        steps:
            - attach_workspace:
                at: /tmp/ws
            - run:
                command: |
                    ls -l /usr/lib/jvm /home/circleci/*
                    sudo mkdir -p /usr/lib/jvm /home/circleci
                    rmdir /home/circleci/project
                    for d in home/circleci/project ; do
                        sudo ln -s /tmp/ws/$d /$d
                    done
            - run:
                command: mvn compile -Djdk.compile.home=/usr/lib/jvm/java-8-openjdk-amd64
                environment:
                    JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
            - persist_to_workspace:
                root: /
                paths:
                    - home/circleci/.m2/repository
                    - home/circleci/project/target
    testsj8:
        docker:
            - image: circleci/openjdk:8-jdk
              environment:
                  discovery.type: single-node
        steps:
            - attach_workspace:
                at: /tmp/ws
            - run:
                command: |
                    ls /usr/lib/jvm /home/circleci/*
                    sudo mkdir -p /usr/lib/jvm /home/circleci
                    for d in home/circleci/.m2 home/circleci/project ; do
                        sudo rm -rf /$d
                        sudo ln -s /tmp/ws/$d /$d
                    done
            - run:
                command: |
                    # If no symbolic name, it's a PR, will not publish results
                    [ -n "$(git symbolic-ref HEAD 2>/dev/null )" ] && PUBLISH="deploy sonar:sonar"
                    echo "publishing jobs: $PUBLISH"
                    mvn install $PUBLISH -Dmaven.test.skip=true -Dmaven.main.skip=true -s .circleci/settings.xml -Djdk.compile.home=/usr/lib/jvm/java-8-openjdk-amd64 -Dsonar.login=$SONARCLOUD_LOGIN
                environment:
                    JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
            - store_test_results:
                path: target/surefire-reports
    testsj11:
        docker:
            - image: circleci/openjdk:11-jdk
              environment:
                  discovery.type: single-node
        steps:
            - attach_workspace:
                at: /tmp/ws
            - run:
                command: |
                    ls /usr/lib/jvm /home/circleci/*
                    sudo mkdir -p /usr/lib/jvm /home/circleci
                    for d in home/circleci/.m2 home/circleci/project ; do
                        sudo rm -rf /$d
                        sudo ln -s /tmp/ws/$d /$d
                    done
            - run:
                command: |
                    # If no symbolic name, it's a PR, will not publish results
                    [ -n "$(git symbolic-ref HEAD 2>/dev/null )" ] && PUBLISH="deploy sonar:sonar"
                    echo "publishing jobs: $PUBLISH"
                    mvn install $PUBLISH -Dmaven.test.skip=true -Dmaven.main.skip=true -s .circleci/settings.xml -Djdk.compile.home=/usr/lib/jvm/java-11-openjdk-amd64
                environment:
                    JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
            - store_test_results:
                path: target/surefire-reports
    savecache:
        docker:
            - image: circleci/openjdk:11-jdk
              environment:
                  discovery.type: single-node
        steps:
            - attach_workspace:
                at: /tmp/ws
            - run:
                command: |
                    ls /usr/lib/jvm /home/circleci/*
                    sudo mkdir -p /usr/lib/jvm /home/circleci
                    for d in home/circleci/.m2 home/circleci/project ; do
                        sudo rm -rf /$d
                        sudo ln -s /tmp/ws/$d /$d
                    done
            - save_cache:
                paths:
                    - ~/.m2
                key: jrdsagent-{{ checksum "pom.xml" }}
            
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - checkout
      - build:
          requires:
              - checkout
      - testsj8:
          requires:
              - build
      - testsj11:
          requires:
              - build
      - savecache:
          requires:
              - testsj8
              - testsj11
      
